
SHOTODOL_CORE_SIGNALING_CSOURCES=$(wildcard $(SHOTODOL_WEB_HOME)/libs/signaling/vsrc/*.c)
SHOTODOL_CORE_SIGNALING_VSOURCE_BASE=$(basename $(notdir $(SHOTODOL_CORE_SIGNALING_CSOURCES)))
OBJECTS+=$(addprefix $(SHOTODOL_WEB_HOME)$(OBJDIR_COMMON)/, $(addsuffix .o,$(SHOTODOL_CORE_SIGNALING_VSOURCE_BASE)))

