
SYNC_PROTO_CLASSIFIER_CSOURCES=$(wildcard $(SYNC_SWITCH_HOME)/libs/syncclassifier/vsrc/*.c)
SYNC_PROTO_CLASSIFIER_VSOURCE_BASE=$(basename $(notdir $(SYNC_PROTO_CLASSIFIER_CSOURCES)))
OBJECTS+=$(addprefix $(SYNC_SWITCH_HOME)/build/.objects/, $(addsuffix .o,$(SYNC_PROTO_CLASSIFIER_VSOURCE_BASE)))
