
SHOTODOL_HTTP_GATEWAY_CSOURCES=$(wildcard $(SYNC_SWITCH_HOME)/libs/http_gateway/vsrc/*.c)
SHOTODOL_HTTP_GATEWAY_VSOURCE_BASE=$(basename $(notdir $(SHOTODOL_HTTP_GATEWAY_CSOURCES)))
OBJECTS+=$(addprefix $(SHOTODOL_WEB_HOME)/build/.objects/, $(addsuffix .o,$(SHOTODOL_HTTP_GATEWAY_VSOURCE_BASE)))
